# CRP 4680/5680 Mid Term Prep

## String, Floats and Integers

In [1]:
"Hello World"

'Hello World'

In [2]:
x= 4.8
print(int(x))

4

## Dataframes

In [3]:
import pandas as pd
import datetime as dt
import geopandas as gpd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Building from Dictionaries

In [4]:
city_names = ["Ithaca", "New York City", "Albany", "Elmira", "Syracuse"]
city_populations = [32108, 20100000,  99224,26523,148620]
city_medincome = [31169, 38293, 26918, 27292, 38794]

# A pandas dataframe is defined by pd.DataFrame()
# Often times we call it a "df" : dataframe
city_df = pd.DataFrame({'City':city_names,
                        'Population':city_populations,
                        'MedIncome': city_medincome})

# What structure is inside the DataFrame() call?
city_df

            City  Population  MedIncome
0         Ithaca       32108      31169
1  New York City    20100000      38293
2         Albany       99224      26918
3         Elmira       26523      27292
4       Syracuse      148620      38794

### Working with CSV files

In [5]:
parking = pd.read_csv('parking_citations.csv')
parking.head()

/var/folders/s7/f39th_ms4knd5dm45hnn81dc0000gn/T/ipykernel_432/919954895.py:1: DtypeWarning: Columns (0,16) have mixed types. Specify dtype option on import or set low_memory=False.
  parking = pd.read_csv('parking_citations.csv')

,ticket_number,issue_date,issue_time,meter_id,marked_time,rp_state_plate,plate_expiry_date,vin,make,body_style,...,agency,violation_code,violation_description,fine_amount,agency_desc,color_desc,body_style_desc,loc_lat,loc_long,geocodelocation
0,1129198954,2024 Jan 01 12:00:00 AM,"1,724",NaN,0,CA,0,NaN,TOYO,NaN,...,2,NaN,NaN,58,LAX CURRENT,NaN,NaN,33.942089,-118.404577,POINT (-118.404577 33.942089)
1,4578090661,2024 Jan 01 12:00:00 AM,220,NaN,0,CA,202308,NaN,HOND,PA,...,56,4000(a)1,EXPIRED REGISTRATION,50,56 - DOT - CENTRAL,SILVER,PASSENGER CAR,34.053516,-118.276019,POINT (-118.2760192 34.0535159)
2,4577607156,2024 Jan 01 12:00:00 AM,249,NaN,0,CA,202306,NaN,TOYT,PU,...,53,88.66,ELECTRIC CHARGING STATION SPACES,58,53 - DOT - VALLEY,GREY,PICK-UP TRUCK,34.190315,-118.548174,POINT (-118.5481743 34.1903155)
3,4577667426,2024 Jan 01 12:00:00 AM,318,NaN,0,CA,202408,NaN,JEEP,PA,...,54,5200,DISPLAY OF PLATES,25,54 - DOT - HOLLYWOOD,WHITE,PASSENGER CAR,34.104186,-118.309133,POINT (-118.3091334 34.1041856)
4,4577607123,2024 Jan 01 12:00:00 AM,229,NaN,0,CA,202403,NaN,HOND,PA,...,53,22514,FIRE HYDRANT,68,53 - DOT - VALLEY,BLACK,PASSENGER CAR,34.200874,-118.525018,POINT (-118.5250176 34.2008738)

In [6]:
## access the columns with list

In [7]:
## take a look at the data types

In [8]:
## show 2nd-5th columns of the dataframe

In [9]:
### show the last two rows of the df

In [10]:
### show the last 2 columns and first 5 rows

In [11]:
## change fine amount from string to an integer

In [12]:
## find rows where fine amount is an na value

In [13]:
## replace the na values with the mode of the fine amounts using the lambda apply function

In [14]:
## filter for cars with the make JEEP or TOYO or CHEV
## try using the df['columns'] == value formate

In [15]:
## now repeat the same exercise using the isin()

In [16]:
## how many citations are there or each of the filtered car makes

In [17]:
## which car make has the highest fine amount

### Geodataframe, Geopandas and Census

In [18]:
## make the df into a gdf

In [19]:
## bring the TIGER lines for LA 

year = 2020
state_fips = "06"

url = f"https://www2.census.gov/geo/tiger/TIGER{year}/TRACT/tl_{year}_{state_fips}_tract.zip"

tracts = gpd.read_file(url)
tracts.head()

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,06,029,004402,06029004402,44.02,Census Tract 44.02,G5020,S,1865739,0,+35.5917343,-119.3337642,"POLYGON ((-119.33828 35.58143, -119.33827 35.5..."
1,06,047,000802,06047000802,8.02,Census Tract 8.02,G5020,S,2321653,0,+37.3433591,-120.5854604,"POLYGON ((-120.59599 37.34121, -120.59596 37.3..."
2,06,085,501402,06085501402,5014.02,Census Tract 5014.02,G5020,S,522620,0,+37.3453341,-121.8665169,"POLYGON ((-121.87381 37.34412, -121.87361 37.3..."
3,06,005,000102,06005000102,1.02,Census Tract 1.02,G5020,S,456204155,7940832,+38.5496993,-120.2509786,"POLYGON ((-120.61016 38.4156, -120.61 38.41577..."
4,06,029,004901,06029004901,49.01,Census Tract 49.01,G5020,S,1459379,0,+35.7837173,-119.2462266,"POLYGON ((-119.25262 35.79043, -119.25259 35.7..."

In [20]:
from census import Census
from us import states
from key import CENSUS_KEY

In [21]:
states.CA.fips

'06'

In [22]:
## bring in census data for la county

c= Census(CENSUS_KEY)

la_tracts = c.acs5.get( # start here each time
    ('B01001_001E', 'B01001_004E', 'B01001_005E', 'B01001_006E'), # specify the variables we want
    {'for': 'tract:*', # specify the geometry resolution we want
     'in': 'state:06 county:037'}, # speciffy the geometry bounds. In this case, the state of NY
    year=2020, # specify the year
)

In [23]:
la_df = pd.DataFrame(la_tracts)
la_df.head()

   B01001_001E  B01001_004E  B01001_005E  B01001_006E state county   tract
0       3006.0         49.0         70.0         17.0    06    037  199700
1       3618.0        279.0         86.0        100.0    06    037  199801
2       2419.0        129.0         50.0         50.0    06    037  199802
3       2687.0        112.0         98.0         33.0    06    037  199900
4       2203.0         18.0         37.0         30.0    06    037  201110

In [24]:
## in the la_df create a new column called GEOID

In [25]:
## merge the tracts with the la_tracts data set

In [26]:
## rename B01001_001E to total_pop, B01001_004E to male_under5, B01001_005E to male_5to9 and B01001_006E to male_10to14

merged = merged.rename(columns = {'B01001_001E' : 'total_pop',
                         'B01001_004E' : 'male_under5',
                         'B01001_005E' : 'male_5to9',
                         'B01001_006E' : 'male_10to14'
                        })

NameError: name 'merged' is not defined

In [ ]:
## plot the JEEP and TOYOTA car makes and the number of total population in each tract 

fig, ax= plt.subplots(1,2, figsize = (10,8))

make_geo =

### Spatial Weights

In [ ]:
from libpysal import io
from libpysal import weights

In [ ]:
##using the merged data set create knn = 6 weights matrix

In [ ]:
## create a spatially lagged total population variable